version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1-stretch
    working_directory: /go/src/github.com/cybozu-go/aptutil
    steps:
      - checkout
      - run: git branch --set-upstream-to=origin/$CIRCLE_BRANCH $CIRCLE_BRANCH
      - run: make bootstrap
      - run: make test
      - run: make archive
